
export const INIT_WATCH_MOVIE = 'INIT_WATCH_MOVIE';
export const ADD_MOVIES = 'ADD_MOVIES';
export const ADD_SEATS = 'ADD_SEATS';
export const REMOVE_SEATS = 'REMOVE_SEATS';
export const REMOVE_MOVIES = 'REMOVE_MOVIES';
export const SET_MOVIES = 'SET_MOVIES';
export const SET_SEATS = 'SET_SEATS';
export const INIT_MOVIES = 'INIT_MOVIES';
export const FETCH_MOVIES_FAILED = 'FETCH_MOVIES_FAILED';
 
export const BOOK_MOVIE_SUCCESS = 'BOOK_MOVIE_SUCCESS';
export const BOOK_MOVIE_FAIL = 'BOOK_MOVIE_FAIL';
export const BOOK_MOVIE_START = 'BOOK_MOVIE_START';
export const BOOK_MOVIE_FINISH = 'BOOK_MOVIE_FINISH';
export const BOOK_MOVIE = 'BOOK_MOVIE';
export const BOOKING_INIT = 'BOOKING_INIT'; 

export const FETCH_ORDERS = 'FETCH_ORDERS';
export const FETCH_ORDERS_START = 'FETCH_ORDERS_START';
export const FETCH_ORDERS_SUCCESS = 'FETCH_ORDERS_SUCCESS';
export const FETCH_ORDERS_FAIL = 'FETCH_ORDERS_FAIL';

export const AUTH_CHECK_STATE = 'AUTH_CHECK_STATE';
export const AUTH_USER = 'AUTH_USER';
export const AUTH_START = 'AUTH_START';
export const AUTH_SUCCESS = 'AUTH_SUCCESS';
export const AUTH_FAIL = 'AUTH_FAIL';
export const AUTH_CHECK_TIMEOUT = 'AUTH_CHECK_TIMEOUT';
export const AUTH_INITIATE_LOGOUT = 'AUTH_INITIATE_LOGOUT';
export const AUTH_LOGOUT = 'AUTH_LOGOUT';


export const SET_AUTH_REDIRECT_PATH = 'SET_AUTH_REDIRECT_PATH';